### ISSUE TITLE
Checksum Invalid 2

### ISSUE THREAD

**Issue by Maximilianos** [yahoo/flux-examples#101]
Hey I commented on closed issue #69 with an issue I had with the react-router example.

It appears that due to the timestamp the rendered react components re-render on the client.

Here's part of my last comment on that thread illustrating this: 

---

```javascript
    console.log(document.getElementById('app').innerHTML);

    Router.run(app.getAppComponent(), HistoryLocation, function (Handler, state) {
        context.executeAction(navigateAction, state, function () {
            React.withContext(context.getComponentContext(), function () {
                React.render(React.createFactory(Handler)(), mountNode, function () {
                    bootstrapDebug('React Rendered');
                });

                console.log(document.getElementById('app').innerHTML);
            });
        });
    });
```

Diffing the output now I notice two differences in the logged strings, first is that `data-react-checksum="-2082033167"` was missing in the client-rendered string (is this to be expected when server-client disagree?) and probably more importantly the timestamps were different: 
```
// server                                                                        ↓
<em style="font-size:.8em;" data-reactid=".172htz1i3nk.2">Wed Feb 04 2015 17:18:53 GMT+0200 (GTB Standard Time)</em>
// client                                                                        ↓
<em style="font-size:.8em;" data-reactid=".172htz1i3nk.2">Wed Feb 04 2015 17:18:54 GMT+0200 (GTB Standard Time)</em>
```

**Comment by mridgway** [comment]
I'm able to reproduce. I'll look into this. Thanks for reporting.

**Comment by mridgway** [comment]
Hi @Maximilianos, I finally got around to fixing this. Check it out to see if it works for you now. Thanks for reporting!
