### ISSUE TITLE
getting component context inside the component

### ISSUE THREAD

**Issue by trungpham** [yahoo/flux-examples#102]
I have a plugin that populate the component context, however, I am not able to access the component context.
Though, after mixing in the fluxible,Mixin. I can see context.executionAction, and context.getStore just fine.

Do you know how I can get the access to the component Context that populated by my plugin? Thanks.

**Comment by trungpham** [comment]
FYI, my plugin was able to populate the actionContext without any problem, but not the component context.

**Comment by trungpham** [comment]
Also, I am using the react router example. I suspect that somehow the react router dropped the component context.
In the server.js, context.getComponentContext() returns the right context.

**Comment by trungpham** [comment]
it turns out that the FluxibleMixin did not add the plugin component context to the contextTypes white list.

**Comment by mridgway** [comment]
We are unable to populate arbitrary contextTypes in the FluxibleMixin since it is static. We recommend creating a component mixin specifically for your plugin with the methods that it exposes.

**Comment by lingyan** [comment]
From another angle, it is better for each component that uses context function(s) to define contextTypes inside the component, without the plugin providing a mixin for this purpose only.    When the plugin provides a mixin, the mixin can't really predict which function(s) is needed by a component, and whether they should be mandatory or optional.   So it is actually better for the components themselves to define contextTypes as part of its spec.

**Comment by mridgway** [comment]
@lingyan +1
