### ISSUE TITLE
Is the fluxible-plugin-rr used anywhere?

### ISSUE THREAD

**Issue by Maximilianos** [yahoo/flux-examples#103]
If not, is it meant to be used somewhere? how is it meant to be used? Thank you!

**Comment by redonkulus** [comment]
Which plugin is that? I do not need it on npm.

**Comment by Maximilianos** [comment]
Its a file in the react-router example: https://github.com/yahoo/flux-examples/tree/master/react-router/plugins

**Comment by Maximilianos** [comment]
It doesn't seem to do anything, so was wondering how(if) one is meant to use it and/or what it is demonstrating.

**Comment by lingyan** [comment]
I assume you meant `fluxible-plugin-router`.   It is used to provide routing related functions to fluxible contexts, mainly, `makePath()` to the fluxible componentContext, if you use [flux-router-component](https://github.com/yahoo/flux-router-component).

The fluxible-router example in this repo uses it in the following way:
1. First, it plugs the plugin to the Fluxible: https://github.com/yahoo/flux-examples/blob/master/fluxible-router/app.js#L14
2. In Nav component, it passes the `routeName` to `NavLink` component: https://github.com/yahoo/flux-examples/blob/master/fluxible-router/components/Nav.jsx#L28
3. `NavLink` component uses `makePath()` to create the url: https://github.com/yahoo/flux-router-component/blob/master/lib/NavLink.js#L91

**Comment by redonkulus** [comment]
@Maximilianos it seems like it was started but never implemented. Perhaps it could be used for generating URLs based on the router configuration. Similar to how `fluxible-plugin-router` works for our own router. @mridgway can explain more.

**Comment by mridgway** [comment]
Initially tried making the react-router integration a plugin but found that it was unnecessary. Looks like my exploration code snuck into the commit. It can be removed.

**Comment by Maximilianos** [comment]
I had a sneaking suspicion that was the case :) ok glad for confirmation made pr: https://github.com/Maximilianos/flux-examples/pull/1
