### ISSUE TITLE
Initialising user with react-router 

### ISSUE THREAD

**Issue by shyambalu-sellaco** [yahoo/flux-examples#105]
Following on from #37. I was wondering how to do this without breaking the flux flow and using react router.

I am trying to achieve on boot initialise and auth user from session storage, if a token exists and redirect to main application. If not then show full page login screen. 

My route handlers look something like this, as you can see it's a shared root.

```
    <Route handler={Application}>
        <Route handler={Authed}>
            <Route name="about" handler={About}/>
            <DefaultRoute name="home" handler={Home}/>
        </Route>
        <Route handler={NotAuthed}>
            <Route name="login" handler={Login}/>
        </Route>
    </Route>
```

I am thinking on boot 

```
 action fires to check auth -> update user store 
                            -> transition to correct page based on auth
```

however this breaks flux flow.

**Comment by redonkulus** [comment]
@shyambalu-sellaco you could fire different actions depending on whether the user is authenticated. Then your store can set the appropriate state for your application.

**Comment by bringking** [comment]
With the react-router example, I don't see a way to intercept the routing to check is a user is logged in, the "executeAction" action is just a post route notification right? it is not actually doing any routing..

**Comment by bringking** [comment]
@shyambalu-sellaco did you ever figure out a pattern for this?

**Comment by redonkulus** [comment]
Closing old issues. Please re-open in the yahoo/fluxible repo if needed.
