### ISSUE TITLE
Need to set a content-type header in server.js

### ISSUE THREAD

**Issue by steveme** [yahoo/flux-examples#107]
Currently res.write happens without setting a content-type.

Should have  
```
res.set('Content-Type', 'text/html'); 
```
before the res.write's in each of the server.js files

**Comment by steveme** [comment]
Or just use res.send(html) instead of res.write(...);res.end(); and the fact it's a string will trigger the content-type of text/html

**Comment by jedireza** [comment]
Thanks for creating an issue. We'll be sure to double check this.

**Comment by redonkulus** [comment]
I'm looking into this now.

**Comment by redonkulus** [comment]
Fixed in https://github.com/yahoo/flux-examples/commit/c24bfb18a87dd3d49fe450ccadc1eee1cb763606
