### ISSUE TITLE
Client only example

### ISSUE THREAD

**Issue by jedireza** [yahoo/flux-examples#108]
Let's create an example that doesn't have the server half. Let's demonstrate regular API access via superagent/xhr directly.

**Comment by mattapperson** [comment]
+1

**Comment by mattapperson** [comment]
As of right now I am having this issue trying to do this: https://github.com/yahoo/flux-examples/issues/94

**Comment by robink** [comment]
+1

**Comment by mridgway** [comment]
Instead of making a separate client-only application, it's actually probably easier for us to make it so all of the examples work as server-only, client-only (except for services), or isomorphic. This would be a simple check in the client.js to determine whether to do nothing, call the navigate action, or rehydrate respectively.

**Comment by jedireza** [comment]
Interesting idea.

> client-only (except for services)...

Could you clarify a bit?

A couple other questions that came to mind were:

 - How would we start an app in a different mode (server, client, isomorphic)?
 - How would we abstract the actions and service calls to work in client-side-only mode while demonstrating recommended conventions and expected use cases?

**Comment by mridgway** [comment]
Anything using fetchr would need the server component as well. So we'd have to start the server regardless if it was client rendered or not.

> How would we start an app in a different mode (server, client, isomorphic)?

For server only, I guess we already get that for free, but we could set a query param to disable client bootstrap. Client only, we would allow just opening an index.html that includes the client bootstrapping Javascript. Basically, in this case `window.App` would be undefined and the `<div id="app">` would be empty, so we would know whether it was server rendered or not. If it's not, then we just execute the `navigateAction`.

**Comment by jedireza** [comment]
I see what you mean, thanks for clarifying.

> Anything using fetchr would need the server component as well. So we'd have to start the server regardless if it was client rendered or not.

Originally I was thinking of a client-only app with the assumption that we wouldn't use `fetchr` or data services. Demonstrating a Fluxible (client-only) app that uses a REST API for example.

**Comment by mridgway** [comment]
Right, I think what I'm trying to say is that it's only a few more lines to get a server-only app working as client-only as well. We could do it with the routing examples pretty easily.

**Comment by jedireza** [comment]
Yup same page. I like it. Should I open a new ticket for creating a REST example?

**Comment by Guru107** [comment]
@jedireza Have you tried creating client only example.

**Comment by jedireza** [comment]
@Guru107 I have not.

**Comment by redonkulus** [comment]
@Guru107 @mridgway actually committed a change a few weeks ago to the chat example that does client side only rendering when passing in `?render=0`. You can use that as an example:

https://github.com/yahoo/flux-examples/tree/master/chat#usage
