### ISSUE TITLE
[react-router] Upgrade to react-router@1.0

### ISSUE THREAD

**Issue by mridgway** [yahoo/flux-examples#116]
Depends on https://github.com/rackt/react-router/pull/590

**Comment by tleunen** [comment]
Can we have an example with react-router beta?

**Comment by redonkulus** [comment]
Agreed, we should update our example to react-router 1.0. We will try to get to it soon.

**Comment by jeffreywescott** [comment]
Hopefully this helps someone else: see #153

**Comment by cesarandreu** [comment]
react-router 1.0 will have support for using a route store with HOCs, and I think they're killing willTransitionTo. Once that's working and you can take a similar approach to fluxible-router, handling actions can be left up to the user.

As an example of what can be achieved right now with react-router v1.0.0-beta3, check out [redux-react-router](https://github.com/acdlite/redux-react-router/).

There's a good discussion about it [here](https://github.com/acdlite/redux-react-router/issues/1).

**Comment by mridgway** [comment]
Makes sense. I will change this issue to upgrading to react-router 1.0

**Comment by mmahalwy** [comment]
How would we do a data fetch before render with the new react-router?

**Comment by pheuter** [comment]
This has changed in the latest version of react router v1.0. For example, `Router.run` is no longer available.

**Comment by mmahalwy** [comment]
@pheuter im gonna put an example up in the next few days

**Comment by pheuter** [comment]
@mmahalwy sweet! ping when u do

**Comment by LeafInStrom** [comment]
@mmahalwy any progress?

**Comment by mmahalwy** [comment]
I been hacking through this for a while:
https://github.com/mmahalwy/react-fluxible-starter

I am not very content with it just yet, the reason being I really dislike the way I have to do the hook for async data before rendering from the server. See: https://github.com/mmahalwy/react-fluxible-starter/blob/master/server.js#L29

If anyone has better suggestions I am game

**Comment by mridgway** [comment]
`react-router@1.0.0` has dropped: https://github.com/rackt/react-router/blob/master/CHANGES.md#v100

**Comment by sfarthin** [comment]
Anyone working on this ?

**Comment by mmahalwy** [comment]
@sfarthin you can look at my starter, which i havent maintained for a while but it'd help as a guiding stick: https://github.com/mmahalwy/react-fluxible-starter you should use https://github.com/rackt/async-props instead of RoutingContext

**Comment by redonkulus** [comment]
Closing old issues. Please re-open in the yahoo/fluxible repo if needed.
