### ISSUE TITLE
Add unit/functional tests

### ISSUE THREAD

**Issue by jenswegar** [yahoo/flux-examples#121]
One of the biggest issues I have with Fluxible right now is that, as a newcomer, it is very difficult to figure out how to properly write unit and functional tests for an application based on Fluxible, especially if not using Jest. It would be great if you could add tests to these examples so we would have at least something to start off with.

**Comment by redonkulus** [comment]
We have full unit and functional tests on our Fluxible.io website here: https://github.com/yahoo/fluxible.io/tree/master/tests

I will add a link in the readme to make it clearer.
