### ISSUE TITLE
chat: should i be seeing automatic chat updates across browsers?

### ISSUE THREAD

**Issue by laurencefass** [yahoo/flux-examples#131]
firefox test only.

im only seeing updates on a manual update of the browser. im not sure if node.js is meant to be socketing between browser instances for "live updates".

advice sought. 

thanks

laurence

**Comment by laurencefass** [comment]
my command line output...

laurencefass@host100:/var/www/flux-examples/chat$ sudo npm run dev

> flux-example-chat@0.0.0 dev /var/www/flux-examples/chat
> grunt --gruntfile ../Gruntfile.js --taskName chat

Running "clean:0" (clean) task
>> 1 path cleaned.

Running "concurrent:dev" (concurrent) task
Running "nodemon:dev" (nodemon) task
[nodemon] v1.3.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./chat/server.js`
Running "webpack:dev" (webpack) task
 34% 6/15 build modulesListening on port 3000
Version: webpack 1.7.3      
        Asset     Size  Chunks             Chunk Names
    client.js  1.42 MB       0  [emitted]  main
client.js.map  1.71 MB       0  [emitted]  main

**Comment by mridgway** [comment]
We haven't implemented web sockets or any kind of polling into the chat example, so no you won't see live updates.

**Comment by laurencefass** [comment]
ok. thanks.
