### ISSUE TITLE
server side async route action 

### ISSUE THREAD

**Issue by lionng429** [yahoo/flux-examples#139]
when I refresh a page with an async route action, the corresponding store did not emit change properly so that onChange in corresponding component was not fired. any idea?

**Comment by mridgway** [comment]
Not sure I totally understand. Are you trying to re-execute the same page that you're currently on?

**Comment by lionng429** [comment]
It is a full browser refresh

**Comment by mridgway** [comment]
If you are rendering server-side, you will not see `change` events being emitted. If you are client-side, the same thing is true for the initial bootstrapping because the components have not been rendered yet.

**Comment by lionng429** [comment]
I see, so is there any way to preloading data to the app?

**Comment by mridgway** [comment]
The idea is that you call `executeAction` to get your application to a certain state and then you call `React.render`. So you should be preloading your data through actions.

**Comment by lionng429** [comment]
just like the dynamicpage in fluxible router exmaple? I tried to wrap the `context.dispatch` with `setTimeout`, when I do a full browser refresh on `/page/:id`, it showed `content for page with id undefined` on browser

**Comment by mridgway** [comment]
Yeah, just like the fluxible router example. Are you rendering on the server or only on the client?

**Comment by lionng429** [comment]
Oh, it's my fault, I missed the `done()` outside the `setTimeout` function. We can then use typeof window to decide if we wait for the async calls or not.

Thank you for your time mrigway, I will close the this issue for now.

**Comment by mridgway** [comment]
:+1: glad you figured it out.
