### ISSUE TITLE
How to handle data requests that require authentication in isomorphic app?

### ISSUE THREAD

**Issue by lionng429** [yahoo/flux-examples#140]
As we are using ajax calls on both client and server side, with a full browser refresh, requests will becomes server-to-server requests with new session, making me impossible to fetch data according to the identity of the signed in user.

I am wondering if I have messed up the concept with isomorphic Fluxible React App. Should I make such requests under route actions? or I should place these calls under component level?

Thank you so much for your time in advance.

**Comment by redonkulus** [comment]
Closing old issues. Please re-open in the yahoo/fluxible repo if needed.
