### ISSUE TITLE
fluxible-router example: Title doesn't update on navigation

### ISSUE THREAD

**Issue by jissjohn** [yahoo/flux-examples#142]
https://github.com/yahoo/flux-examples/blob/master/fluxible-router/components/Application.js#L21

Title doesn't update on navigation between 'Home' and 'About' page.
I was able to get it working using newProps.ApplicationStore.pageTitle instead of newProps.pageTitle though I am not sure if that's a good fix.

**Comment by mridgway** [comment]
Yup, looks like the state object changed. Thanks for reporting! We'll get it fixed up.

**Comment by mridgway** [comment]
Fixed via https://github.com/yahoo/flux-examples/pull/143

**Comment by jissjohn** [comment]
:+1:  Thanks!
