### ISSUE TITLE
react-router: context is not passed to sub components

### ISSUE THREAD

**Issue by trungpham** [yahoo/flux-examples#144]
I'm following the react router example. But I'm having the hard time making the context available to the sub component.

my subcomponent declares the contextTypes properties, and I have a plugin that populates the componentContext.

The key of the context is available, but the value is always set to null. Very strange.

**Comment by trungpham** [comment]
```
React.renderToString( React.createElement(
                            FluxibleComponent,
                            { context: context.getComponentContext() },
                            Component()
                        ));
```
```
            plugComponentContext: function (componentContext) {
                componentContext.currentUser = currentUser;
                componentContext.currentGroup = currentGroup;
            },
```
```
    contextTypes: {
        request: React.PropTypes.object,
        currentUser: React.PropTypes.object,
        currentGroup: React.PropTypes.object,
        router: React.PropTypes.func,
        display: React.PropTypes.object
    },
```

The only property that is not set to null is router. I suspect that it has something to do with react-router.

**Comment by mridgway** [comment]
`FluxibleComponent` only sets `getStore` and `executeAction` in your context. If you have custom context types you will need to propagate them yourself. You could create your own `FluxibleComponent` based on our implementation.

**Comment by icodeforlove** [comment]
This seems very weird when trying to get Fluxible plugins that take advantage of `plugComponentContext` to work.

I used your suggestion, and this did fix the issue. Is this really the standard way of achieving this?
