### ISSUE TITLE
Reference to fluxible-plugin-routr

### ISSUE THREAD

**Issue by Geoff-Ford** [yahoo/flux-examples#147]
The flux-examples README.md makes reference to fluxible-plugin-routr being used within the example applications. As far as I can tell this used to be the case within the chat example but the plugin has now been swapped out for fluxible-router (see commit below):

https://github.com/yahoo/flux-examples/commit/ac0e31183e8adf84cfbefa92bf79a5e26f128d1c

**Comment by redonkulus** [comment]
@Geoff-Ford thanks for the tip. Fixed it https://github.com/yahoo/flux-examples/commit/0683e7b4ea70b6e504ce0bdd83c40a0d44daca54
