### ISSUE TITLE
Server-side rendering with async data

### ISSUE THREAD

**Issue by mmahalwy** [yahoo/flux-examples#148]
Can you provide an example to server-side rendering after actions have finished resolving and dispatching?

**Comment by redonkulus** [comment]
@mmahalwy [todomvc](https://github.com/yahoo/flux-examples/tree/master/todo) does that now. For example, take a look at the [showTodos](https://github.com/yahoo/flux-examples/blob/master/todo/actions/showTodos.js) action, which will call for data and then dispatch once its received. The `done()` call is used [on the server](https://github.com/yahoo/flux-examples/blob/master/todo/server.js#L45) to know when to call [React.renderToString](https://github.com/yahoo/flux-examples/blob/master/todo/server.js#L60).

**Comment by mmahalwy** [comment]
@redonkulus +1

That does suffice. Eventually I found a solution but what would have been great is to show on the routes file. I will provide a link soon - just at work :)
