### ISSUE TITLE
Is there a way to avoid use dangerouslySetInnerHTML ?

### ISSUE THREAD

**Issue by eriknyk** [yahoo/flux-examples#158]
I'm asking if there is a way to avoid the use of dangerouslySetInnerHTML, into the root component,
usually Html.jsx, just because I just pass some callbacks and properties to the children, and I would to know If we can set the jsx node as normal tag there.

something like this:

```
            <html>
              <head></head>
              <body>
                <div id="app" dangerouslySetInnerHTML={{__html: this.props.markup}}></div>

                <script src="/js/vendor/jquery/jquery-1.11.1.min.js"></script>
                <script dangerouslySetInnerHTML={{__html: this.props.state}}></script>
              </body>
            </html>
```

to this

```
            <html>
              <head></head>
              <body>
                <Application someProp={someVal} someCallback={this.someCallback.bind(this)}></Application>

                <script src="/js/vendor/jquery/jquery-1.11.1.min.js"></script>
                <script dangerouslySetInnerHTML={{__html: this.props.state}}></script>
              </body>
            </html>
```

Best Regards.

**Comment by mridgway** [comment]
Is there a reason you don't trust the output of markup? It's also generated using React.renderToString, so it should be safe to use. I'm not sure how the callback would work and I believe you'd still need to use `dangerouslySetInnerHTML` with the output of that callback somewhere.
