### ISSUE TITLE
sh: 1: nodemon: not found?

### ISSUE THREAD

**Issue by jcs12311** [yahoo/flux-examples#160]
i already `run npm install`, and it success.
then,`cd todo` and `npm run dev`.
but i got this:
sh: 1: nodemon: not found

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! flux-example-todo@0.0.0 dev: `node webpack-dev-server.js & PORT=3001 nodemon server.js -e js,jsx`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the flux-example-todo@0.0.0 dev script 'node webpack-dev-server.js & PORT=3001 nodemon server.js -e js,jsx'.
npm ERR! This is most likely a problem with the flux-example-todo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node webpack-dev-server.js & PORT=3001 nodemon server.js -e js,jsx
npm ERR! You can get their info via:
npm ERR!     npm owner ls flux-example-todo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jc/project/flux-examples/todo/npm-debug.log

**Comment by jcs12311** [comment]
ubuntu 12.04,x64.
node v4.0.0

**Comment by Aadriya** [comment]
use npm install nodemon --save
