### ISSUE TITLE
What is Fluxible?

### ISSUE THREAD

**Issue by mridgway** [yahoo/flux-examples#70]
Our end goal was to have a complete solution for developers to get a project up and running on top of our isomorphic Flux libraries. The implementation of this solution has been a debate within our team, so I want to open this discussion up to get feedback from our community to guide our direction for Fluxible.

We already have a strong starting point for building an application in our examples, but we need to provide an easier way for developers to start an application other than forking or copy/pasting code. Right now we have all of the building blocks necessary for creating an application, but there's no server implementation that brings it all together.

It's also important that we have a full architecture so that we can evolve our libraries to meet the demands of external projects. Building out a full solution will help drive the other libraries' direction rather than it coming mainly from our (Yahoo's) internal projects as it is now.

### Should we focus on a full framework or just generators? 

We already have an internal framework implementation that could be abstracted for public use, but would developers prefer this over a less opinionated generator that ties the libraries together?

### What is "fluxible"?

Should `fluxible` package be that full framework/generator or rename `fluxible-app` as it is now to `fluxible` and simply be a library?

If we're building a full framework (as was our initial plan) the `fluxible` package becomes the clear library name for this. If we're building generators instead of the framework, it becomes more likely that `fluxible-app` as it is now *is* the `fluxible` library.

So `fluxible` can be a library, a framework, or just an architecture that is supported by other libraries.

### How should we implement the server?

Should we support multiple server implementations (express, hapi, etc.) or be opinionated and let variants be community driven? Or leave server implementation out of it entirely?

Let us know where you think the Fluxible project should evolve.

**Comment by Prestaul** [comment]
+1 for @emkay. I love this effort and I want it to succeed, but I'm more likely to use it if it is a set of unopinionated tools than as a framework, and if it requires generators to get started then I certainly will steer clear. My vote: compose-able components and as little boilerplate as possible.

**Comment by tindli** [comment]
+1 for @emkay too. I see it as a set of tools. Examples for the most popular servers would be nice.

**Comment by jmuel** [comment]
Yeah, the most interesting part of Fluxible to me is the Dehydrate/Rehydrate concept. Being able to preprocess the flux state on the server and then pass it across in whole is incredibly intuitive and powerful, but most of the other stuff in fairly standard flux. If I had my preference Fluxible would be functionality for rehydrate, dehydrate and some mixins for stores/actions/dispatchers to make them work with that concept.

**Comment by arjansingh** [comment]
+1 for @emkay's idea as well. Keep them libraries and see if good design patterns emerge. If you get several of those, then it's time to abstract them into a framework that builds on top of the library.

**Comment by mridgway** [comment]
Looks like we're all on the same page then. My proposal is to rename the `fluxible-app` package to `fluxible` and make that the main package. There will not be a framework that we provide, only examples for using Fluxible with the server of your choice. Anything else we provide as far as generators would become separate packages.

Thanks everyone for your feedback! We're excited to see what 2015 brings for isomorphic Flux applications.

**Comment by jedireza** [comment]
:sparkles::+1::sparkles:

**Comment by mdressman** [comment]
Sounds like a great plan, thanks so much for all your work on this @mridgway @jedireza.  I'm really enjoying the full suite of packages.

**Comment by tindli** [comment]
@mridgway @jedireza @lingyan
Thank you so much for the fluxible package! 
Thanks to the developers and supporters of this project! You are all doing a great job.

**Comment by TYRONEMICHAEL** [comment]
I definitely think a generator is a must. Even though you have eliminated quite a but of the boilerplate with Fluxible and react store events, there is still quite a bit to write when setting up a store. Eg. Store -> action -> constant. Would be great to have this automated.

**Comment by mridgway** [comment]
The rename of `fluxible-app` to `fluxible` has happened. I'm going through all of our projects to update the dependencies.

**Comment by mridgway** [comment]
I went through the Fluxible repos and updated their dependencies to point to `fluxible`. Separate tickets should be created for other action items.
