### ISSUE TITLE
Server: action context or just context?

### ISSUE THREAD

**Issue by gpbl** [yahoo/flux-examples#76]
Looking to `server.js`, [here](https://github.com/yahoo/flux-examples/blob/master/todo/server.js#L45) in the todo app we are passing the app context, but [here](https://github.com/yahoo/flux-examples/blob/master/chat/server.js#L42) in the chat app we are using `context.getActionContext()`. What is the difference in this case? When should we use one or the other?

Thanks

**Comment by mridgway** [comment]
They are actually the same thing. The `context.executeAction()` is a shortened way of calling `context.getActionContext().executeAction()`. We should make this more consistent. Perhaps we should get rid of `context.executeAction()` to remove confusion.

**Comment by gpbl** [comment]
:+1:  for removing `context.executeAction()`. Thanks!
