### ISSUE TITLE
Store with immutable data

### ISSUE THREAD

**Issue by tindli** [yahoo/flux-examples#86]
One of the goals of every react app should be to put state as high in the component hierarchy
as possible (ideally near the top). As it gets easier to reason about an app by eliminating state 
spread all over components, calling setState() on a component near the top can slow down the 
app due to the potentially large number of comparisons in the virtual DOM tree 
(especially on component lists or nested data).

Putting state near the top is reactjs best practice and mimics the concept of flux.
Using it and having a fast app requires to use immutable data structures in the stores.

This way, shouldComponentUpdate() can be easily implemented - and the app remains being fast.

Although shouldComponentUpdate() should only be used when an actual app performs poorly,
we should really show the concept/use of immutable data objects together with flux.

This is not an issue with this great implementation of flux but I think it would greatly show the full
potential of the unidirectional data flow provided through flux.

**Comment by mridgway** [comment]
:+1: Adding immutable.js would be great.

**Comment by tindli** [comment]
Yeah immutable.js would be an awesome addition. I think it is very important to use a lib that supports cursors; since immutable.js does this, it should work great for flux stores (to be able to directly reference/manipulate nested data)

By using immutable objects, state is required only in a few top level components. Things like the "editing" state for Todos would be hold in the store... making all components render from props only.

Going even further, I guess it should be possible possible to have a single component (I think the application component/root of the component tree) listening to store events. Having only one central listener should simplify the application architecture as well.

**Comment by tindli** [comment]
We could also use a light implementation of cursors https://github.com/caseywebdev/cursors
together with reacts immutability helpers. I think that would be everything we really need for getting a basic (sufficient?) implementation...

In general:
I don't know how immutables will work together with something like controlled components.... and
if the store would have to hold all transient UI states...

It would be cool to have some discussion about that.... (and immutables for flux in general)

**Comment by tindli** [comment]
I have done some research and found a very interesting project that implemented immutables and the flux pattern: https://github.com/optimizely/nuclear-js

This might help and give some valuable ideas when we are going down the immutable path.

One of the things I am still not sure is how component state can be handled in such an approach because having everything in application state, how can 2 components depend on the same store data, but still having individual component states (e.g. having their background changed by clicking them - this is what I see as component state since another component using the same data should not be affected...).

Maybe I am too confused at this point to really see the whole thing...
Nevertheless immutable + cursors seem to be pretty well suited for the flux pattern...

What do you think?

**Comment by tindli** [comment]
bump.
Any thoughts about this topic??? 
Is yahoo using immutable constructs already in their implementation?

**Comment by mridgway** [comment]
I haven't had a lot of time to research this yet, but we have a few teams using immutable.js successfully from within their stores.

**Comment by tindli** [comment]
thanks for the response.
I guess immutable.js should play nice with the concepts of flux... so 
converting an app that runs with standard mutable js objects to immutable.js should not be 
that big of a deal; hopefully.
