### ISSUE TITLE
Html.jsx is a nondescript filename

### ISSUE THREAD

**Issue by cobookman** [yahoo/flux-examples#88]
File: https://github.com/yahoo/flux-examples/blob/master/chat/components/Html.jsx

Instead of Html.jsx call it something like Main.jsx or Boilerplate.jsx.  Not really sure on the name.

The issue with Html.jsx is that it infers that this component is in charge of all Html.  And no other component will render Html.

**Comment by mridgway** [comment]
Agreed, this could be named better. `Wrapper` is something we've used before for this type of template.

**Comment by jedireza** [comment]
I don't mind the `Html.jsx` filename. I like `Wrapper.jsx` less.

**Comment by timReynolds** [comment]
I don't really see the issue with calling it Html.jsx but Template.jsx also seemed valid.

**Comment by cobookman** [comment]
HyperText Markup Language doesn't make sence as a name for a react component.  Its like having a javascript file called `javascript.js`.  It just seems weird.  

Maybe `Document.jsx` makes more sense?

**Comment by mysterycommand** [comment]
+1 for `Document.jsx`

**Comment by jedireza** [comment]
FWIW: I've also used `Template.jsx` in other projects.

**Comment by kumarharsh** [comment]
Name it `index.jsx`, like the index.html file is already served as the default html file for servers.

**Comment by Maximilianos** [comment]
A typical name for wrapper files like this is: `Layout.jsx`

**Comment by mridgway** [comment]
I don't think we're going to change this. Html.jsx is fine since the top level is the <html> tag.

**Comment by cobookman** [comment]
@mridgway.  I'd really re-consider closing this.  Html.jsx is a really confusing filename.  
I'm all for layout.jsx, or even `HTMLFactory.jsx`

`html.jsx` confused me when I first started with fluxible projects.  Better to lower the learning curve, and increase readability no?

**Comment by cesarandreu** [comment]
I use `Html.jsx` too. It makes sense to me.
