### ISSUE TITLE
Please confirm Todo behavior

### ISSUE THREAD

**Issue by localnerve** [yahoo/flux-examples#91]
First, thank you for a great example to get familiar with Fluxible and Friends.

Can you please confirm the Todo example executes the update action twice (and sends two xhr requests)?
When I go to debug it in Chrome DevTools, the behavior stops.
However, I can recreate this behavior so long as I don't set breakpoints.

As a flux/react noob, what is the "correct" way to debug this stuff? I've never had such a simple thing be so elusive. Thanks again for this example.

**Comment by redonkulus** [comment]
@localnerve you are correct. The TodoItem component calls the `handleSubmit` method [onBlur](https://github.com/yahoo/flux-examples/blob/master/todo/components/TodoItem.jsx#L81) of the input field and [onKeyDown](https://github.com/yahoo/flux-examples/blob/master/todo/components/TodoItem.jsx#L83) to handle cases when the user hits the `enter` key. We need to prevent the item from trying to save when its already in progress.

/cc @jedireza

**Comment by jedireza** [comment]
Good catch @localnerve, this has been fixed.
