### ISSUE TITLE
Using Fluxible in NON-isomorphic app, getStore - undefined is not a function

### ISSUE THREAD

**Issue by voronianski** [yahoo/flux-examples#94]
Unfortunately docs are not informative in this case and all examples contain `server.js/client.js/app.js` pattern.

I would like to run Fluxible app only on client, that's how entry file looks like:

```javascript
'use strict';

require('es5-shim');
require('es5-shim/es5-sham');

var React = require('react');
var Fluxible = require('fluxible');

var ProductStore = require('./stores/ProductStore');
var CartStore = require('./stores/CartStore');
var App = require('./components/App.jsx');

var app = new Fluxible();

app.registerStore(ProductStore);
app.registerStore(CartStore);

React.render(
    React.createElement(App, {context: app.createContext()}),
    document.getElementById('flux-app')
);
```

**But I receive** `Uncaught TypeError: undefined is not a function` **in StoreMixin's line 67 getStore method** - https://github.com/yahoo/fluxible/blob/master/mixins/StoreMixin.js#L67

That's how the example component looks like:

```javascript
var Cart = React.createClass({
    mixins: [StoreMixin],

    statics: {
        storeListeners: {
            _onChange: [CartStore]
        }
    },

    _getStateFromStores: function () {
        return {
            products: this.getStore(CartStore).getAddedProducts(),
            total: this.getStore(CartStore).getTotal()
        };
    },

    getInitialState: function () {
        return this._getStateFromStores();
    },

    checkout: function () {
        if (!this.state.products.length) {
            return;
        }
        this.props.context.executeAction(cartCheckout, this.state.products);
    },

    render: function () {
        var products = this.state.products;

        var hasProducts = products.length > 0;
        var nodes = !hasProducts ?
            <div>Please add some products to cart.</div> :
            products.map(function (p) {
                return <Product key={p.id}>{p.title} - &euro;{p.price} x {p.quantity}</Product>;
            });

        return (
            <div className="cart uk-panel uk-panel-box uk-panel-box-primary">
                <div className="uk-badge uk-margin-bottom">Your Cart</div>
                <div className="uk-margin-small-bottom">{nodes}</div>
                <div className="uk-margin-small-bottom">Total: &euro;{this.state.total}</div>
                <button className="uk-button uk-button-large uk-button-success uk-align-right"
                    onClick={this.checkout}
                    disabled={hasProducts ? '' : 'disabled'}>
                    Checkout
                </button>
            </div>
        );
    },

    _onChange: function () {
        this.setState(this._getStateFromStores());
    }
});
```

**Comment by voronianski** [comment]
Ok, so I got it working in the way app is initialized on the server side - https://github.com/yahoo/flux-examples/blob/master/todo/server.js#L45

**Comment by mattapperson** [comment]
I am seeing this too (though the error is now on `https://github.com/yahoo/fluxible/blob/master/mixins/FluxibleMixin.js#L69` )

Any hints on how to do this without server side rendering?

**Comment by mattapperson** [comment]
FWIW I am using ReactRouter

**Comment by mattapperson** [comment]
The answer when you want a 100% client side solution would be something like this:
```
/** @jsx React.DOM */

(function () {
  'use strict';

    var React = require('react');
    var Fluxible = require('fluxible');

    var app = new Fluxible();
    app.registerStore(require('./stores/ApplicationStore'));
    var context = app.createContext();

    React.withContext(context.getComponentContext(), function () {
        React.render(<Handler/>, document.body);
    });
}());

```

**Comment by raphaelparent** [comment]
#### React.withContext deprecated

`React.withContext` is deprecated and I don't seem to find any equivalent/solution for the new react version.

##### This is the error that I get.
```
Warning: Failed Context Types: Required context `executeAction` was not specified in `TagContainer`. 
Warning: Failed Context Types: Required context `getStore` was not specified in `TagContainer`.
```

And in `TagContainer` constructor I log `context` received from the params.
```
constructor(props, context) {
	super(props, context);
	console.log(context);
}
```

And the result is :
```
Object {executeAction: undefined, getStore: undefined}
```

There is obviously a problem with how I set/call/connect the context or my store.

Anyone have an idea for 100% client side solution using `react: 0.14` and `react-dom: 0.14` ?

P.S.: I also looked up `context.createElement` which was undefined and nowhere to be found in the fluxible doc (probably deprecated). The new `server.js` in the To Do example used a specific method of `react-dom` to render on the server (maybe I missed something there) but does't seem to led to any solutions. I also tried with the `@connectToStore` decorator and I get an error that `context.getStore is undefined`.

**Comment by raphaelparent** [comment]
#### Client side solution with newer versions of react and fluxible

```
"dependencies": {
    "fluxible": "^1.0.0",
    "fluxible-addons-react": "^0.2.2",
    "react": "^0.14.0",
    "react-dom": "^0.14.0"
}
```

I managed to make it work on the client exclusively with something that looks like this.

```
import createElement from 'fluxible-addons-react/createElementWithContext';
import Fluxible from 'fluxible';
import React from 'react';
import ReactDOM from 'react-dom';
import YourComponent from './YourComponent';
import YourStore from './stores/YourStore'


let container = document.createElement('div');
let app = new Fluxible({ component: YourComponent });
let props = {};

document.body.appendChild(container);

app.registerStore(YourStore);

app.rehydrate({}, function(err, context) {

	if(err)
		throw err;

	window.context = context;

	ReactDOM.render(createElement(context, props), container);

});
```

This code is mainly from the [client.js file](https://github.com/yahoo/fluxible/blob/master/examples/todo/client.js) in the todo examples.

Basically, I rehydrate the app with an empty object and render the component with the context provided from the rehydrate callback.

Then I __connect to the store__ with a decorator in my component.
```
connectToStores([YourStore], (context, props) => {
	return {
		data: context.getStore(YourStore).getData()
	}
})
```

Now the __context__ is available in the constructor ( `constructor(props, context) ` ) or anywhere else ( `this.context` )

And the values return within the __decorator callback__ are available through the props.

I hope this helps some people :smiley:
